### ISSUE TITLE
Dark mode and glass mode causing problem with app which shows popup on selecting keys and autohotkey function

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#99]
I use a program called pantherbar which shows popup on selecting text 

![image](https://user-images.githubusercontent.com/43289832/119270335-d34a5380-bc19-11eb-82f8-b5b1129d718e.png)

But I when I use dark mode/glass no popup appears. 

Also using Autohotkey I have modified few keys to various functions but upon dark/glass mode such and other Autohotkey functions do not execute.

**Comment by gileli121** [comment]
Thanks for the report.
I will check what I can do next week

**Comment by gileli121** [comment]
@jakkaas 
I downloaded the utility and tried to reproduce the issue with google chrome, notepad, and word.
In all of these programs, I enabled dark-mode and checked if I see the utility toolbar.
In all cases, I saw it.

So maybe the bug was fixed from the utility side?
Do you still have this bug or I can close this ticket?

The only issue that I did saw is that the WindowTop toolbar shows above the utility toolbar

![image](https://user-images.githubusercontent.com/17680514/131214944-7451ca79-ae0f-47f4-a8da-e8b5c1aacc7d.png)

I can try to fix it if you want

**Comment by jakkaas** [comment]
Hello Gileli. It's still not working for me. Even when I have disabled all my background apps. Even autohotkey doesn't word/send command when dark mode/smart opacity mode is activated.

**Comment by gileli121** [comment]
@jakkaas 
What Pantherbar version do you have?
Maybe they fixed something at some point so in the last version you no longer get the issue.
Please try to update Pantherbar to the last version and see if it fixed it... If not then we will see what else we can check

**Comment by jakkaas** [comment]
Hey, I am using Pantherbar Pro version v2.1.1.0 and Window top version 5.4.13.

**Comment by jakkaas** [comment]
Hello Gileli,

1. https://drive.google.com/file/d/1EEyoC8mlxq8XtrhScOe4LI6xQLDey_6c/view?usp=sharing

2.https://drive.google.com/file/d/1R5HwBPpJqxHsBtM9FbtkLDv3LS_FrD24/view?usp=sharing




1) In the first recording, you can see that I have disabled all background apps which might hinder with window top and then tested it. As you can see, in normal mode, pantherbar easily pop up but when dark mode is activated it doesn't. Also, when I activate autohotkey and use it (such as quickly switching between two apps on pressing caps lock), it is functioning but when I use it when dark mode is activated it doesn't work.


2) In video 2 you can see that I use fastkey app (an app based on autohotkey). In normal mode when I press hotkey a menu popup but when darkmode is activated, it doesn't.

I have also tested with the new build you have shared with others, but same result.

Thanks

**Comment by gileli121** [comment]
@jakkaas 
Sorry for the late reply.
I totally forgot about this issue.

Anyway, I saw the videos.
The issue you showed in the first video should be fixed much more easily from the "pantherbar" side.
Please ask the developer of pantherbar to fix it. The issue is that the "pantherbar" toolbar is not placed on top of the dark-mode "mask" window

**Comment by jakkaas** [comment]
Ok. I have contacted the developer. Can you solve the another issue of AHK function not working when the window is in dark mode?

**Comment by jakkaas** [comment]
Hey just shifted to windows 11 and formatted the pc. AHK is working fine on Dark mode and Glass mode. So thats slover.


But there is issue with Pantherbar popup. 

Instead of detecting that i am selecting text in dark/glass mode, it is detecting it as i am double clicking it. 

Any reason you can guess?

**Comment by DavidHJong** [comment]
the incompatibility between windowtop darkmode and autohotkey script still exists. 
to replicate this, 

1. on windows 10,
2. install windowtop 5.26,
3. install autohotkey 2,
4. create a text file, copy the following script, save it with extension `.ahk`, then double click it to run it. 

```
#Requires AutoHotkey v2.0
#SingleInstance force

; -----------------------------------------------------------------------------------------key remapping section

; Right-hand copy & paste
![::Send "^c"
!]::Send "^v"
!'::Send "^x"
!`;::Send "^a"
```

5. when you disable the darkmode in windowtop, these hotkeys should work. when you enable the darkmode, these hotkeys stop working.

**Comment by mmortal03** [comment]
I'm noticing the same buggy behavior with a different dark mode utility called "Dark Mode Any App" when used alongside Autohotkey. I wonder if it is occurring with windowtop and "Dark Mode Any App" for similar reasons. I found an older thread on the AHK forums suggesting to try "Run with UI Access" on the AHK script, but, unfortunately, that does not fix the problem currently: https://www.autohotkey.com/boards/viewtopic.php?style=1&t=111108

I'm using a pretty simple AHK script to intercept some Bluetooth headset button presses as virtual keys, that way I can remap their functions. In the process of writing the script, I discovered that "Dark Mode Any App" breaks the intercepting of the button presses whenever an app has been converted to dark mode by it and is in focus. Google AI seems to think that it could be a "greedy" message hook in the utility that doesn't pass media signals along?
